name: ipr2025q1
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  meta: 1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.15
  source_gen: 2.0.0 
  analyzer: 7.4.5 

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true